---
title: Greenwich Comedy Festival
timezone: UTC
collections:
  line-up:
    title: Line-up
    output: true
  posts:
    title: Posts
    output: false
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
url: https://www.greenwichcomedyfestival.co.uk
description: Greenwich Comedy Festival returns this summer for another series of unmissable
  shows!
permalink: pretty
exclude:
- bower.json
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- bower_components
- ".gitignore"
- assets/scss
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: false
highlighter: rouge
company: 57 Festivals Ltd
address: National Maritime Museum, Greenwich
email: info@greenwichcomedyfestival.co.uk
google_site_verification: pqGndzwmQkEKSTgKHo610nlM0DuQgngEzzJldUbq084
analytics: UA-49569208-1
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
social:
  facebook: https://www.facebook.com/greenwichcomedyfestival
  instagram: https://www.instagram.com/greenwichcomedyfestival
  twitter: https://twitter.com/greenwichcomedy
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
imgix:
  source: https://greenwich-comedy-festival.imgix.net
